### Logistic Regression Implementation 
- on synthetically generated data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

RANDOM_STATE = 15

In [2]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1200, n_features=9, n_classes=2, random_state=RANDOM_STATE)

In [3]:
df = pd.DataFrame(X, columns=[f'feature{i}' for i in range(1, 10)])

df['target'] = y

In [4]:
df.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,target
0,-0.678084,-1.168784,-0.396585,-0.750901,0.318124,-0.214755,0.713357,-1.965636,0.724709,0
1,1.273290,1.168108,0.248769,0.703696,-1.379711,-0.534346,-1.105935,0.656240,0.978545,1
2,1.286952,0.609599,-0.828121,0.726689,-0.806056,0.447817,-0.608994,-0.753998,0.648640,1
3,0.504017,0.865311,0.008795,-2.290390,0.076449,-1.239904,-0.412666,0.197809,-1.036871,1
4,0.995913,2.121625,0.949027,0.755207,-2.610291,0.478512,-2.047316,0.321279,1.944647,1


In [5]:
X = df.iloc[:, :-1]
X

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9
0,-0.678084,-1.168784,-0.396585,-0.750901,0.318124,-0.214755,0.713357,-1.965636,0.724709
1,1.273290,1.168108,0.248769,0.703696,-1.379711,-0.534346,-1.105935,0.656240,0.978545
2,1.286952,0.609599,-0.828121,0.726689,-0.806056,0.447817,-0.608994,-0.753998,0.648640
3,0.504017,0.865311,0.008795,-2.290390,0.076449,-1.239904,-0.412666,0.197809,-1.036871
4,0.995913,2.121625,0.949027,0.755207,-2.610291,0.478512,-2.047316,0.321279,1.944647
...,...,...,...,...,...,...,...,...,...
1195,-0.821371,0.787249,0.908182,0.188496,-1.197456,1.175213,-0.844392,-0.364134,1.088655
1196,-1.289123,1.530549,-1.007069,-2.284822,-1.758207,-1.118845,-1.430726,-1.091654,1.202619
1197,1.379029,1.256367,-0.406451,1.985111,-0.432469,0.474312,-0.800311,1.189936,-0.633864
1198,1.202351,1.443892,-2.207257,0.209109,-0.708097,0.193385,-0.997891,-1.411072,-0.389956


In [6]:
y = df.iloc[:, -1]
y

0       0
1       1
2       1
3       1
4       1
       ..
1195    1
1196    1
1197    1
1198    1
1199    0
Name: target, Length: 1200, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=RANDOM_STATE)

In [8]:
print(f"X_train Shape: {X_train.shape}")
print(f"X_test Shape: {X_test.shape}")

X_train Shape: (900, 9)
X_test Shape: (300, 9)


In [9]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression()
logistic.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


#### Why not fit_tranform() X_test?
Since make_classification generates data that is already fairly normalized, you might not notice a big difference here, but in real-world data, skipping scaling with Logistic Regression can seriously hurt performance.

In [10]:
y_pred = logistic.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [11]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

score=accuracy_score(y_test, y_pred)
print("Accuracy Score =", score)
print("\n")
print("Classification Report:\n", classification_report(y_test ,y_pred))
print("Confusion Matrix:\n" ,confusion_matrix(y_test, y_pred))

Accuracy Score = 0.9233333333333333


Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.89      0.92       147
           1       0.90      0.95      0.93       153

    accuracy                           0.92       300
   macro avg       0.93      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

Confusion Matrix:
 [[131  16]
 [  7 146]]


#### Hyperparameter Tuning and Crossvalidation

GridSearchCV

In [12]:
model = LogisticRegression()
penalty = ['l1', 'l2', 'elasticnet']
c_values = [100, 10, 1, 0.1, 0.01]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [13]:
params = dict(penalty=penalty, C=c_values, solver=solver)

In [14]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

In [15]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold()

In [16]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator=model,
                   param_grid=params,
                   scoring='accuracy',
                   cv=cv,
                   n_jobs=-1)

In [17]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')


In [18]:
grid.fit(X_train, y_train)

,estimator,LogisticRegression()
,param_grid,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l1'


In [19]:
grid.best_params_

{'C': 100, 'penalty': 'l1', 'solver': 'liblinear'}

In [20]:
grid.best_score_

np.float64(0.9133333333333333)

In [21]:
y_pred2 = grid.predict(X_test)

In [22]:
score = accuracy_score(y_test, y_pred2)
print("Accuracy Score =", score)
print("Classification Score:\n", classification_report(y_test, y_pred2))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred2))

Accuracy Score = 0.9266666666666666
Classification Score:
               precision    recall  f1-score   support

           0       0.95      0.90      0.92       147
           1       0.91      0.95      0.93       153

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300

Confusion Matrix:
 [[132  15]
 [  7 146]]


- Randomized Search CV

In [23]:
from sklearn.model_selection import RandomizedSearchCV

randomcv=RandomizedSearchCV(estimator=model, param_distributions=params, cv=5, scoring='accuracy')

In [24]:
randomcv.fit(X_train,y_train)

,estimator,LogisticRegression()
,param_distributions,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,n_iter,10
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [25]:
randomcv.best_score_

np.float64(0.9133333333333333)

In [26]:
randomcv.best_params_

{'solver': 'liblinear', 'penalty': 'l2', 'C': 10}

In [27]:
y_pred3=randomcv.predict(X_test)

In [28]:
score = accuracy_score(y_test, y_pred3)
print("Accuracy Score =", score)
print("Classification Score:\n", classification_report(y_test, y_pred3))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred3))

Accuracy Score = 0.9266666666666666
Classification Score:
               precision    recall  f1-score   support

           0       0.95      0.90      0.92       147
           1       0.91      0.95      0.93       153

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300

Confusion Matrix:
 [[132  15]
 [  7 146]]


#### Logistic Regression for multiclass classification

In [29]:
X, y = make_classification(n_samples=1000, n_features=10, n_informative=3, n_classes=3, random_state=15)

In [30]:
pd.DataFrame(X).head()

,0,1,2,3,4,5,6,7,8,9
0,-1.286132,-0.648334,1.044115,-0.469715,0.789859,-0.083727,-1.647309,-1.316412,1.011910,-0.898063
1,-0.222224,2.083232,1.191114,-1.354527,-0.956992,1.696028,-1.070406,0.981403,-1.628798,1.377594
2,-0.431963,0.375745,-1.370334,0.819214,0.345243,1.389447,-1.904130,1.292602,0.925545,0.232705
3,-0.912633,0.986988,-0.690042,2.014628,-0.442260,0.590347,-1.819353,1.560938,0.823755,0.517762
4,-0.367056,1.667892,0.879172,2.214276,1.846338,-0.894047,1.543838,0.931103,-1.015210,1.061845


In [31]:
X_train, X_test, y_train, y_test=train_test_split(X, y,
                                               test_size=0.25,
                                               random_state=42)

In [32]:
from sklearn.multiclass import OneVsRestClassifier

model = OneVsRestClassifier(LogisticRegression())

In [33]:
model.fit(X_train, y_train)

,estimator,LogisticRegression()
,n_jobs,None
,verbose,0
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None


In [34]:
model.n_features_in_

10

In [35]:
model.classes_

array([0, 1, 2])

In [36]:
model.decision_function(X_train)

array([[-4.26553504, -0.46226358, -0.11938499],
       [ 0.15574673, -1.40267761, -2.6202539 ],
       [-3.93247612, -1.35173612,  0.62461383],
       ...,
       [-3.63681147,  0.69218834, -1.35843087],
       [-2.18433201,  1.13231733, -2.87682988],
       [-3.15784906, -4.32331784,  2.27143926]], shape=(750, 3))

In [37]:
model.get_params()

{'estimator__C': 1.0,
 'estimator__class_weight': None,
 'estimator__dual': False,
 'estimator__fit_intercept': True,
 'estimator__intercept_scaling': 1,
 'estimator__l1_ratio': None,
 'estimator__max_iter': 100,
 'estimator__multi_class': 'deprecated',
 'estimator__n_jobs': None,
 'estimator__penalty': 'l2',
 'estimator__random_state': None,
 'estimator__solver': 'lbfgs',
 'estimator__tol': 0.0001,
 'estimator__verbose': 0,
 'estimator__warm_start': False,
 'estimator': LogisticRegression(),
 'n_jobs': None,
 'verbose': 0}

In [38]:
y_pred = model.predict(X_test)

In [39]:
y_pred

array([2, 1, 2, 1, 1, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 1, 2, 0, 0, 2, 2, 1, 2, 2, 2, 1,
       2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 1, 0, 2, 0, 1,
       2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 0, 2, 2, 2, 1, 2, 0,
       2, 2, 0, 0, 0, 2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 1,
       2, 0, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 1,
       0, 2, 1, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2,
       0, 0, 1, 2, 2, 0, 0, 2, 1, 2, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 2, 1,
       0, 1, 0, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 2, 0, 0, 2, 2, 2])

In [40]:
model.predict_proba(X_test)

array([[1.13073983e-04, 1.78835287e-01, 8.21051639e-01],
       [2.21334448e-01, 6.57396598e-01, 1.21268954e-01],
       [4.80356728e-06, 2.53640459e-01, 7.46354738e-01],
       [1.19201764e-01, 8.16095016e-01, 6.47032204e-02],
       [9.45172038e-02, 8.82178871e-01, 2.33039252e-02],
       [8.57121413e-01, 4.40329884e-02, 9.88455987e-02],
       [7.97649510e-01, 6.66904393e-02, 1.35660051e-01],
       [9.23368796e-01, 2.05387213e-02, 5.60924827e-02],
       [4.00499171e-02, 3.68333115e-01, 5.91616968e-01],
       [7.94802216e-01, 1.96195490e-01, 9.00229364e-03],
       [7.15358557e-04, 3.44551779e-01, 6.54732862e-01],
       [3.44680668e-01, 5.86354329e-01, 6.89650032e-02],
       [1.45750340e-01, 5.48482176e-03, 8.48764838e-01],
       [2.61142736e-02, 4.20634587e-01, 5.53251140e-01],
       [9.06817799e-03, 3.68351785e-01, 6.22580037e-01],
       [2.87885535e-02, 3.84259243e-02, 9.32785522e-01],
       [1.05826656e-02, 1.62039325e-01, 8.27378009e-01],
       [6.70825079e-01, 3.19625

In [41]:
score = accuracy_score(y_test, y_pred)
print("Accuracy Score =", score)
print("Classification Score:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy Score = 0.788
Classification Score:
               precision    recall  f1-score   support

           0       0.84      0.83      0.84        78
           1       0.84      0.73      0.78        91
           2       0.70      0.81      0.75        81

    accuracy                           0.79       250
   macro avg       0.79      0.79      0.79       250
weighted avg       0.79      0.79      0.79       250

Confusion Matrix:
 [[65  7  6]
 [ 3 66 22]
 [ 9  6 66]]
